global_costmap:
    global_frame:       map
    robot_base_frame:   base_link
    update_frequency:   3.0
    publish_frequency:  0.0
    static_map: true
    rolling_window: false
    width: 3.0
    height: 3.65
