PoseFollower:
  k_trans: 3.0
  k_rot: 3.0
  tolerance_trans: 0.3
  tolerance_rot: 0.3
  tolerance_timeout: 1.5
  holonomic: false
  samples: 100
  max_vel_lin: 0.3
  min_vel_lin: 0.3
  max_vel_th: 0.3
  min_vel_th: -0.3
#  min_in_place_vel_th: 0.2
#  in_place_trans_vel: 0.05
#  trans_stopped_velocity: 0.0001
#  rot_stopped_velocity: 0.0001
  allow_backwards: true
