PoseFollower:
  k_trans: 2.0
  k_rot: 2.0
  tolerance_trans: 0.3
  tolerance_rot: 1.0
  tolerance_timeout: 0.6
  holonomic: false
  samples: 100
  max_vel_lin: 1.0
  min_vel_lin: 0.21
  max_vel_th: 2.3
  min_vel_th: -2.3
#  min_in_place_vel_th: 0.2
#  in_place_trans_vel: 0.05
  trans_stopped_velocity: 0.18
  rot_stopped_velocity: 0.08
  allow_backwards: true
